//CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const CART_CHANGE_PROPS = 'CART_CHANGE_PROPS';
export const REPLACE_IN_CART='REPLACE_IN_CART'


